os: Visual Studio 2015

environment:
  NODEJS_VERSION: "6"

platform:
  - x86
  - x64

install:
  - ps: Install-Product node $env:NODEJS_VERSION $env:PLATFORM
  - node -e "console.log(process.arch, process.versions)"

  - curl -sSf -o rustup-init.exe https://win.rustup.rs
  - rustup-init.exe -y
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - rustc -V
  - cargo -V

build: false

test_script:
  - cd tests
  - npm test

cache:
  - target
  - C:\Users\appveyor\.cargo\registry
